insert into roles (name) values ('Admin')
insert into roles (name) values ('Cliente')
insert into roles (name) values ('Cajero')

insert into users (first_name, last_name, email, phone) values ('Juan', 'Selva', 'juan.selva@riservi.com', '+5068834343')
insert into users (first_name, last_name, email, phone) values ('Jose', 'Madrigal', 'jose.madrigal@riservi.com', '+3434566666')
insert into users (first_name, last_name, email, phone) values ('Pedro', 'Perez', 'pedro.perez@riservi.com', '+3434566565')
insert into users (first_name, last_name, email, phone) values ('Maria', 'Baltodano', 'maria.baltodano@riservi.com', '+5945945454')
insert into users (first_name, last_name, email, phone) values ('Paula', 'Velasquez', 'paula.velasquez@riservi.com', '+4545454555')
insert into users (first_name, last_name, email, phone) values ('Joanna', 'Navarrete', 'joanna.navarrete@riservi.com', '+4665656566')
insert into users (first_name, last_name, email, phone) values ('Jesus', 'Palacios', 'jesus.palacios@riservi.com', '+6565666334')
insert into users (first_name, last_name, email, phone) values ('Enrique', 'Ortega', 'enrique.ortega@riservi.com', '+3433467844')
insert into users (first_name, last_name, email, phone) values ('Alvin', 'Aviles', 'alvin.aviles@riservi.com', '+0968594883')
insert into users (first_name, last_name, email, phone) values ('Miguel', 'Padilla', 'miguel.padilla@riservi.com', '+3834986048')
insert into users (first_name, last_name, email, phone) values ('Pablo', 'Gonzales', 'pablo.gonzales@riservi.com', '+6887499088')